// The calendar subscription feed, /calendar.ics.
//
// For this finished 2026 edition the feed is a STATIC file, committed at
// public/calendar.ics and generated by scripts/build-calendar.mjs, NOT a Netlify
// function. ESPN dropped date-range scoreboard queries (the old feed's window now
// 400s) and its fiba slug is time-multiplexed, so the per-request function returned
// a hard 502 and would have gone empty once ESPN advanced past 2026. These tests
// guard two things: that the committed file has not drifted from the generator, and
// that it carries the right shape and identity for a subscriber's calendar.
//
// scripts/** sits outside the coverage gate family-wide, so importing the generator
// here does not pull it into the 100% include; the app's own utils/ics.js (which
// actually writes the events) stays covered by its own tests.

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { describe, it, expect } from 'vitest'
import { buildCalendar } from '../scripts/build-calendar.mjs'
import { GAMES } from '../src/data/games.js'

const FEED_PATH = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'calendar.ics')
const committed = readFileSync(FEED_PATH, 'utf8')
const generated = buildCalendar()

describe('static calendar feed', () => {
  it('the committed file is in sync with the generator', () => {
    // If this fails, run `npm run build:calendar` and commit public/calendar.ics.
    expect(committed).toBe(generated)
  })

  it('is a single VCALENDAR with one VEVENT per game', () => {
    expect(committed.startsWith('BEGIN:VCALENDAR')).toBe(true)
    expect(committed.trimEnd().endsWith('END:VCALENDAR')).toBe(true)
    expect(committed.match(/BEGIN:VEVENT/g)).toHaveLength(GAMES.length)
    expect(committed.match(/END:VEVENT/g)).toHaveLength(GAMES.length)
  })

  it('carries this edition\'s identity, not a sibling\'s', () => {
    expect(committed).toContain("PRODID:-//FIBA Women's World Cup 2026 Viewer//EN")
    expect(committed).toContain("X-WR-CALNAME:FIBA Women's World Cup 2026")
    expect(committed).toContain('UID:fibawwc2026-game-1@fibawomensworldcupviewer')
  })

  it('stamps every event with the frozen DTSTAMP, so the file is deterministic', () => {
    const stamps = committed.match(/DTSTAMP:\S+/g)
    expect(stamps).toHaveLength(GAMES.length)
    expect(new Set(stamps)).toEqual(new Set(['DTSTAMP:20260914T000000Z']))
  })

  it('bakes in the real final scores, away-first', () => {
    // Game 1: Japan vs Mali 102-97. The summary orders the game the way the app does
    // and appends the final score.
    expect(committed).toContain('SUMMARY:FIBA WWC: Japan vs Mali (102–97)')
  })

  it('has no all-day events: every 2026 game has a known tip-off time', () => {
    expect(committed).not.toContain('VALUE=DATE')
    expect(committed.match(/DTSTART:\d{8}T\d{6}Z/g)).toHaveLength(GAMES.length)
  })
})
