// Repo-level guards: invariants about the project itself rather than about the
// tournament. Each of these has bitten a viewer in this family before.

import { describe, it, expect } from 'vitest'
import { readFileSync, readdirSync, statSync } from 'node:fs'
import { GAMES } from '../src/data/games.js'
import { join } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const read = (p) => readFileSync(join(ROOT, p), 'utf8')

function walk(dir) {
  const out = []
  for (const name of readdirSync(join(ROOT, dir))) {
    const rel = `${dir}/${name}`
    if (statSync(join(ROOT, rel)).isDirectory()) out.push(...walk(rel))
    else out.push(rel)
  }
  return out
}

describe('scripts runtime', () => {
  const scripts = walk('scripts').filter((f) => f.endsWith('.mjs'))

  it('has scripts to check', () => {
    expect(scripts.length).toBeGreaterThan(0)
  })

  // The data-regeneration scripts run in CI with no `npm install` of app deps.
  // An npm import would work locally and fail in the workflow.
  it('imports only Node built-ins and in-repo source', () => {
    for (const file of scripts) {
      const src = read(file)
      const imports = [...src.matchAll(/^\s*import\s[^'"]*['"]([^'"]+)['"]/gm)].map((m) => m[1])
      for (const spec of imports) {
        const ok = spec.startsWith('node:') || spec.startsWith('./') || spec.startsWith('../')
        expect(ok, `${file} imports "${spec}"`).toBe(true)
      }
    }
  })
})

describe('the ESPN host', () => {
  // site.api.espn.com serves the same routes but 403s from datacenter IPs, so
  // any CI job that touches it fails while local runs pass.
  it('is site.web.api everywhere it appears', () => {
    for (const file of [...walk('scripts').filter((f) => f.endsWith('.mjs')), 'src/services/espn.js']) {
      const src = read(file)
      expect(src, file).not.toMatch(/site\.api\.espn\.com\/apis/)
    }
  })
})

describe('the storage namespace', () => {
  // The hub and all the sibling viewers are served from one origin
  // (ismayc.github.io), so localStorage is shared. A key prefix borrowed from a
  // sibling silently reads and writes that app's preferences.
  it('uses this app’s prefix, never a sibling’s', () => {
    const files = [...walk('src'), 'index.html'].filter((f) => /\.(js|jsx|html)$/.test(f))
    for (const file of files) {
      const src = read(file)
      const keys = [...src.matchAll(/localStorage\.(?:get|set|remove)Item\(\s*'([^']+)'/g)].map(
        (m) => m[1],
      )
      for (const key of keys) {
        expect(key, `${file} uses storage key "${key}"`).toMatch(/^fwwc:/)
      }
      // Nor may a sibling's prefix appear at all.
      for (const foreign of ['wwc:', 'nba:', 'wnba:', 'nfl:', 'mmm:', 'wmm:', 'pl:', 'euro:']) {
        expect(src.includes(`'${foreign}`), `${file} mentions "${foreign}"`).toBe(false)
      }
    }
  })
})

describe('the test timezone pin', () => {
  // Every date-derived assertion in this suite reads the pinned zone. UTC is
  // day-stable for this data; a developer's local zone is not
  // (America/Los_Angeles moves the morning games back a day), so a dropped pin
  // fails locally in a confusing way and passes on an already-UTC CI runner.
  it('is set to UTC in vite.config.js', () => {
    expect(read('vite.config.js')).toMatch(/env:\s*\{\s*TZ:\s*'UTC'\s*\}/)
    expect(process.env.TZ).toBe('UTC')
  })

  it('leaves every game on the same calendar day in UTC as in Berlin', () => {
    // If this ever stops holding, the pin has to change and the day headings
    // need re-checking.
    for (const g of GAMES.filter((x) => x.ko)) {
      const utc = new Date(g.ko).toLocaleDateString('en-CA', { timeZone: 'UTC' })
      const berlin = new Date(g.ko).toLocaleDateString('en-CA', { timeZone: 'Europe/Berlin' })
      expect(utc, `game ${g.num}`).toBe(berlin)
    }
  })
})

describe('generated data', () => {
  it('carries the do-not-edit banner and names its builder', () => {
    for (const file of ['src/data/games.js', 'src/data/teams.js', 'src/data/venues.js']) {
      const src = read(file)
      expect(src, file).toMatch(/GENERATED by scripts\/fetch-tournament\.mjs/)
      expect(src, file).toMatch(/do not edit by hand/)
    }
  })
})
