#!/usr/bin/env node
// Regenerate every file that carries the app mark, from the single definition in
// scripts/lib/mark.mjs:
//
//   public/icon.svg            the mark (home screen, share sheet, anywhere large)
//   public/favicon.svg         identical by design, see below
//   public/icon-192.png        PWA manifest
//   public/icon-512.png        PWA manifest, also the maskable entry
//   public/apple-touch-icon.png iOS home screen
//   public/og-image.svg        only the badge between the MARK markers is rewritten
//
// Run it with `npm run icons`. Needs ImageMagick 7 (`magick`) on PATH.
//
// WHY THE FAVICON KEEPS ITS GROUND. The family default is a transparent tab icon
// (the mark minus its background), but here the ground IS the identity: strip
// Berlin's flag and what is left is a plain basketball, which the NBA and Women's
// March Madness viewers already wear. One app, one mark.
//
// This script VERIFIES its own output rather than trusting the exit code, because
// ImageMagick fails silently and leaves the previous PNG in place: it drops
// strokes, paints url(#id) fills black, ignores clipPath, and discards anything
// inside a rotate() transform. A stale PNG on disk looks exactly like a success.
import { execFileSync } from 'node:child_process'
import { writeFileSync, readFileSync, mkdtempSync, rmSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { tmpdir } from 'node:os'
import { mark, markBadge, BERLIN_RED } from './lib/mark.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const pub = (f) => join(ROOT, 'public', f)
const magick = (args) => execFileSync('magick', args, { encoding: 'utf8' })

const SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
${mark()}
</svg>
`

const HEADER = `<!--
  GENERATED by scripts/make-icons.mjs from scripts/lib/mark.mjs. Do not hand-edit:
  the next \`npm run icons\` overwrites it. Change the art in mark.mjs instead, so
  the tab icon, the home-screen icon and the share card stay the same drawing.
-->
`

const PNGS = [
  ['icon-512.png', 512],
  ['icon-192.png', 192],
  ['apple-touch-icon.png', 180],
]

// The badge on the share card, and the markers make-og-image.mjs's source keeps
// so this script can rewrite just that block.
const OG_START = '<!-- MARK:START -->'
const OG_END = '<!-- MARK:END -->'
const OG_BADGE = { x: 60, y: 46, size: 120 }

const fail = (msg) => {
  console.error(`make-icons: ${msg}`)
  process.exit(1)
}

writeFileSync(pub('icon.svg'), HEADER + SVG)
writeFileSync(pub('favicon.svg'), HEADER + SVG)

const work = mkdtempSync(join(tmpdir(), 'icons-'))
try {
  for (const [name, size] of PNGS) {
    magick(['-background', 'none', pub('icon.svg'), '-resize', `${size}x${size}`, pub(name)])

    const [w, h] = magick([pub(name), '-format', '%w %h', 'info:']).trim().split(' ').map(Number)
    if (w !== size || h !== size) fail(`${name} is ${w}x${h}, expected ${size}x${size}`)

    // The mark is mostly white field and red bands, so a correct render has real
    // spread. A flat image means ImageMagick dropped the art and wrote a blank.
    const stddev = Number(magick([pub(name), '-colorspace', 'gray', '-format', '%[fx:standard_deviation]', 'info:']))
    if (!(stddev > 0.15)) fail(`${name} looks blank (stddev ${stddev.toFixed(4)})`)

    // The bear is the one element that has silently vanished before. Sample the
    // middle band, which is white flag except where the bear and ball sit.
    const dark = Number(
      magick([
        pub(name), '-colorspace', 'gray',
        '-crop', `${size}x${Math.round(size * 0.62)}+0+${Math.round(size * 0.19)}`,
        '-format', '%[fx:mean]', 'info:',
      ]),
    )
    if (!(dark < 0.9)) fail(`${name} has an empty white band: the bear did not render (mean ${dark.toFixed(4)})`)

    console.log(`  ${name.padEnd(20)} ${size}x${size}  stddev ${stddev.toFixed(3)}`)
  }

  // Both red bands must actually be Berlin red, which catches a palette edit that
  // silently fell back to black. Compare the RGB triple, not ImageMagick's pixel
  // string: the PNG carries alpha and prints srgba(...) where the reference swatch
  // prints srgb(...), so the strings never match even when the colors do.
  const rgb = (s) => (s.match(/\d+/g) || []).slice(0, 3).join(',')
  const at = (x, y) => rgb(magick([pub('icon-512.png'), '-format', `%[pixel:p{${x},${y}}]`, 'info:']))
  const want = rgb(magick(['-size', '1x1', `xc:${BERLIN_RED}`, '-format', '%[pixel:p{0,0}]', 'info:']))
  const [top, bottom] = [at(256, 40), at(256, 470)]
  if (top !== want || bottom !== want) fail(`flag bands are ${top} / ${bottom}, expected ${want}`)

  // Rewrite only the badge block inside the share card's source.
  const og = readFileSync(pub('og-image.svg'), 'utf8')
  const a = og.indexOf(OG_START)
  const b = og.indexOf(OG_END)
  if (a === -1 || b === -1) fail(`public/og-image.svg is missing its ${OG_START} / ${OG_END} markers`)
  const badge = markBadge(OG_BADGE.x, OG_BADGE.y, OG_BADGE.size)
  writeFileSync(pub('og-image.svg'), `${og.slice(0, a + OG_START.length)}\n${badge}\n  ${og.slice(b)}`)
  console.log(`  og-image.svg         badge ${OG_BADGE.size}px`)
} finally {
  rmSync(work, { recursive: true, force: true })
}

console.log('make-icons: icon.svg, favicon.svg and the PNGs all rebuilt and verified.')
console.log('make-icons: now run `npm run og:image` to rebuild public/og-image.png.')
