// The tournament board as it stood before tip-off, frozen on September 4, 2026.
//
// WHY THIS FILE EXISTS. src/data/games.js is regenerated by the refresh
// workflow three times a day for the whole 4-13 September window: scores appear
// as games finish, the twelve final-phase records grow real teams and tip-off
// times as the rounds decide them. Every test that asserted against that module
// was really asserting "the tournament has not started", and the whole suite
// went red the moment game 1 went final (run 33897746389, September 4, 2026).
//
// So the derived-logic tests run against this frozen board instead. It is a
// literal copy, never regenerated, and the tests that state results build them
// on top of it through test/helpers/tournament.js.
//
// The two tests that must see the LIVE committed data keep importing
// src/data/games.js directly, and they are the real gate on a refresh:
// test/data.test.js (shape, scores, final-phase records) and
// test/official-schedule.test.js (agreement with FIBA's published sheet).

export const GAMES = [
  { num: 1, stage: 'Group', group: 'A', t1: 'Japan', t2: 'Mali', venue: 'berlinarena', ko: '2026-09-04T11:30:00+02:00', espnId: '401907390', tv: ['HBO Max'] },
  { num: 2, stage: 'Group', group: 'C', t1: 'Australia', t2: 'Puerto Rico', venue: 'maxschmeling', ko: '2026-09-04T11:30:00+02:00', espnId: '401907392', tv: ['HBO Max'] },
  { num: 3, stage: 'Group', group: 'D', t1: 'United States', t2: 'China', venue: 'maxschmeling', ko: '2026-09-04T14:15:00+02:00', espnId: '401907393', tv: ['TNT', 'truTV'] },
  { num: 4, stage: 'Group', group: 'B', t1: 'South Korea', t2: 'Nigeria', venue: 'berlinarena', ko: '2026-09-04T14:30:00+02:00', espnId: '401907391', tv: ['HBO Max'] },
  { num: 5, stage: 'Group', group: 'C', t1: 'Belgium', t2: 'Türkiye', venue: 'maxschmeling', ko: '2026-09-04T17:30:00+02:00', espnId: '401907436', tv: ['HBO Max'] },
  { num: 6, stage: 'Group', group: 'A', t1: 'Spain', t2: 'Germany', venue: 'berlinarena', ko: '2026-09-04T17:45:00+02:00', espnId: '401907394', tv: ['truTV'] },
  { num: 7, stage: 'Group', group: 'D', t1: 'Czechia', t2: 'Italy', venue: 'maxschmeling', ko: '2026-09-04T20:15:00+02:00', espnId: '401907437', tv: ['HBO Max'] },
  { num: 8, stage: 'Group', group: 'B', t1: 'Hungary', t2: 'France', venue: 'berlinarena', ko: '2026-09-04T21:00:00+02:00', espnId: '401907435', tv: ['truTV'] },
  { num: 9, stage: 'Group', group: 'A', t1: 'Mali', t2: 'Spain', venue: 'maxschmeling', ko: '2026-09-05T11:30:00+02:00', espnId: '401907438', tv: ['HBO Max'] },
  { num: 10, stage: 'Group', group: 'B', t1: 'Nigeria', t2: 'Hungary', venue: 'maxschmeling', ko: '2026-09-05T14:15:00+02:00', espnId: '401907439', tv: ['HBO Max'] },
  { num: 11, stage: 'Group', group: 'A', t1: 'Germany', t2: 'Japan', venue: 'maxschmeling', ko: '2026-09-05T18:00:00+02:00', espnId: '401907440', tv: ['HBO Max'] },
  { num: 12, stage: 'Group', group: 'B', t1: 'France', t2: 'South Korea', venue: 'maxschmeling', ko: '2026-09-05T20:45:00+02:00', espnId: '401907441', tv: ['HBO Max'] },
  { num: 13, stage: 'Group', group: 'C', t1: 'Türkiye', t2: 'Australia', venue: 'berlinarena', ko: '2026-09-06T11:30:00+02:00', espnId: '401907442', tv: ['HBO Max'] },
  { num: 14, stage: 'Group', group: 'D', t1: 'China', t2: 'Czechia', venue: 'berlinarena', ko: '2026-09-06T14:30:00+02:00', espnId: '401907443', tv: ['HBO Max'] },
  { num: 15, stage: 'Group', group: 'C', t1: 'Puerto Rico', t2: 'Belgium', venue: 'berlinarena', ko: '2026-09-06T17:45:00+02:00', espnId: '401907444', tv: ['truTV'] },
  { num: 16, stage: 'Group', group: 'D', t1: 'Italy', t2: 'United States', venue: 'berlinarena', ko: '2026-09-06T20:45:00+02:00', espnId: '401907445', tv: ['TNT'] },
  { num: 17, stage: 'Group', group: 'C', t1: 'Belgium', t2: 'Australia', venue: 'berlinarena', ko: '2026-09-07T11:30:00+02:00', espnId: '401907446', tv: ['HBO Max'] },
  { num: 18, stage: 'Group', group: 'C', t1: 'Puerto Rico', t2: 'Türkiye', venue: 'maxschmeling', ko: '2026-09-07T11:30:00+02:00', espnId: '401907450', tv: ['HBO Max'] },
  { num: 19, stage: 'Group', group: 'B', t1: 'Hungary', t2: 'South Korea', venue: 'maxschmeling', ko: '2026-09-07T14:30:00+02:00', espnId: '401907451', tv: ['HBO Max'] },
  { num: 20, stage: 'Group', group: 'B', t1: 'Nigeria', t2: 'France', venue: 'berlinarena', ko: '2026-09-07T14:30:00+02:00', espnId: '401907447', tv: ['truTV'] },
  { num: 21, stage: 'Group', group: 'A', t1: 'Germany', t2: 'Mali', venue: 'berlinarena', ko: '2026-09-07T17:50:00+02:00', espnId: '401907448', tv: ['HBO Max'] },
  { num: 22, stage: 'Group', group: 'A', t1: 'Japan', t2: 'Spain', venue: 'maxschmeling', ko: '2026-09-07T17:50:00+02:00', espnId: '401907452', tv: ['truTV'] },
  { num: 23, stage: 'Group', group: 'D', t1: 'Italy', t2: 'China', venue: 'maxschmeling', ko: '2026-09-07T20:45:00+02:00', espnId: '401907453', tv: ['HBO Max'] },
  { num: 24, stage: 'Group', group: 'D', t1: 'United States', t2: 'Czechia', venue: 'berlinarena', ko: '2026-09-07T20:45:00+02:00', espnId: '401907449', tv: ['TNT', 'truTV'] },
  { num: 25, stage: 'QR', t1: null, t2: null, label1: '2nd Group A', label2: '3rd Group B', venue: null, ko: null, tbdTip: true, date: '2026-09-08', espnId: null },
  { num: 26, stage: 'QR', t1: null, t2: null, label1: '2nd Group B', label2: '3rd Group A', venue: null, ko: null, tbdTip: true, date: '2026-09-08', espnId: null },
  { num: 27, stage: 'QR', t1: null, t2: null, label1: '3rd Group C', label2: '2nd Group D', venue: null, ko: null, tbdTip: true, date: '2026-09-09', espnId: null },
  { num: 28, stage: 'QR', t1: null, t2: null, label1: '3rd Group D', label2: '2nd Group C', venue: null, ko: null, tbdTip: true, date: '2026-09-09', espnId: null },
  { num: 29, stage: 'QF', t1: null, t2: null, label1: 'Winner Group A', label2: 'Winner Game 27', venue: null, ko: '2026-09-10T11:30:00+02:00', espnId: null },
  { num: 30, stage: 'QF', t1: null, t2: null, label1: 'Winner Group B', label2: 'Winner Game 28', venue: null, ko: '2026-09-10T14:30:00+02:00', espnId: null },
  { num: 31, stage: 'QF', t1: null, t2: null, label1: 'Winner Group C', label2: 'Winner Game 25', venue: null, ko: '2026-09-10T17:45:00+02:00', espnId: null },
  { num: 32, stage: 'QF', t1: null, t2: null, label1: 'Winner Group D', label2: 'Winner Game 26', venue: null, ko: '2026-09-10T20:45:00+02:00', espnId: null },
  { num: 33, stage: 'SF', t1: null, t2: null, label1: 'Winner Game 29', label2: 'Winner Game 32', venue: null, ko: null, tbdTip: true, date: '2026-09-12', espnId: null },
  { num: 34, stage: 'SF', t1: null, t2: null, label1: 'Winner Game 30', label2: 'Winner Game 31', venue: null, ko: null, tbdTip: true, date: '2026-09-12', espnId: null },
  { num: 35, stage: '3rd', t1: null, t2: null, label1: 'Loser Game 33', label2: 'Loser Game 34', venue: null, ko: '2026-09-13T16:30:00+02:00', espnId: null },
  { num: 36, stage: 'Final', t1: null, t2: null, label1: 'Winner Game 33', label2: 'Winner Game 34', venue: null, ko: '2026-09-13T20:00:00+02:00', espnId: null },
]
